version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8080'
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: home
      MYSQL_PASSWORD: home
      MYSQL_DATABASE: home
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  adminer:
    image: adminer
    ports:
      - 8081:8080
