version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '127.0.0.1:8000:8080'
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: home
      MYSQL_PASSWORD: home
      MYSQL_DATABASE: home
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - '127.0.0.1:8081:8080'
    networks:
      - default

# VPN workaround for networking
# https://stackoverflow.com/questions/45692255/how-make-openvpn-work-with-docker
networks:
  default:
    external:
      name: local-network
